// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: batch.sql

package db

import (
	"context"
	"database/sql"

	"github.com/lib/pq"
)

const addTrafficDailyBatch = `-- name: AddTrafficDailyBatch :exec
INSERT INTO traffic_daily (user_id, day, up, down)
SELECT unnest($1::bigint[]), $2::bigint, unnest($3::bigint[]), unnest($4::bigint[])
ORDER BY 1
ON CONFLICT (user_id, day) DO UPDATE SET up = traffic_daily.up + excluded.up, down = traffic_daily.down + excluded.down
`

type AddTrafficDailyBatchParams struct {
	UserIds []int64
	Day     int64
	Up      []int64
	Down    []int64
}

func (q *Queries) AddTrafficDailyBatch(ctx context.Context, arg AddTrafficDailyBatchParams) error {
	_, err := q.db.ExecContext(ctx, addTrafficDailyBatch,
		pq.Array(arg.UserIds),
		arg.Day,
		pq.Array(arg.Up),
		pq.Array(arg.Down),
	)
	return err
}

const addTrafficHourlyBatch = `-- name: AddTrafficHourlyBatch :exec
INSERT INTO traffic_hourly (user_id, hour, up, down)
SELECT unnest($1::bigint[]), $2::bigint, unnest($3::bigint[]), unnest($4::bigint[])
ORDER BY 1
ON CONFLICT (user_id, hour) DO UPDATE SET up = traffic_hourly.up + excluded.up, down = traffic_hourly.down + excluded.down
`

type AddTrafficHourlyBatchParams struct {
	UserIds []int64
	Hour    int64
	Up      []int64
	Down    []int64
}

func (q *Queries) AddTrafficHourlyBatch(ctx context.Context, arg AddTrafficHourlyBatchParams) error {
	_, err := q.db.ExecContext(ctx, addTrafficHourlyBatch,
		pq.Array(arg.UserIds),
		arg.Hour,
		pq.Array(arg.Up),
		pq.Array(arg.Down),
	)
	return err
}

const addUserPoolsTraffic = `-- name: AddUserPoolsTraffic :many
INSERT INTO user_pools (user_id, pool_id, used_up, used_down)
SELECT unnest($1::bigint[]), unnest($2::bigint[]), unnest($3::bigint[]), unnest($4::bigint[])
ORDER BY 1, 2
ON CONFLICT (user_id, pool_id) DO UPDATE SET used_up = user_pools.used_up + excluded.used_up, used_down = user_pools.used_down + excluded.used_down
RETURNING user_id, pool_id, traffic_limit, CAST(used_up + used_down AS BIGINT) AS used
`

type AddUserPoolsTrafficParams struct {
	UserIds []int64
	PoolIds []int64
	Up      []int64
	Down    []int64
}

type AddUserPoolsTrafficRow struct {
	UserID       int64
	PoolID       int64
	TrafficLimit sql.NullInt64
	Used         int64
}

// A batch of pool traffic by user and pool; it returns the pools' counters with it.
func (q *Queries) AddUserPoolsTraffic(ctx context.Context, arg AddUserPoolsTrafficParams) ([]AddUserPoolsTrafficRow, error) {
	rows, err := q.db.QueryContext(ctx, addUserPoolsTraffic,
		pq.Array(arg.UserIds),
		pq.Array(arg.PoolIds),
		pq.Array(arg.Up),
		pq.Array(arg.Down),
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AddUserPoolsTrafficRow{}
	for rows.Next() {
		var i AddUserPoolsTrafficRow
		if err := rows.Scan(
			&i.UserID,
			&i.PoolID,
			&i.TrafficLimit,
			&i.Used,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const addUsersTraffic = `-- name: AddUsersTraffic :many
UPDATE users u
SET used_up = u.used_up + t.up, used_down = u.used_down + t.down,
    total_up = u.total_up + t.up + t.pool_up, total_down = u.total_down + t.down + t.pool_down
FROM (SELECT unnest($1::bigint[]) AS id, unnest($2::bigint[]) AS up, unnest($3::bigint[]) AS down,
             unnest($4::bigint[]) AS pool_up, unnest($5::bigint[]) AS pool_down) AS t
WHERE u.id = t.id
RETURNING u.id, u.traffic_limit, CAST(u.used_up + u.used_down AS BIGINT) AS used
`

type AddUsersTrafficParams struct {
	Ids      []int64
	Up       []int64
	Down     []int64
	PoolUp   []int64
	PoolDown []int64
}

type AddUsersTrafficRow struct {
	ID           int64
	TrafficLimit sql.NullInt64
	Used         int64
}

// A traffic batch by user: main traffic counts to the period and the totals, pool traffic
// to the totals only. It returns the period's counters with the batch in them.
func (q *Queries) AddUsersTraffic(ctx context.Context, arg AddUsersTrafficParams) ([]AddUsersTrafficRow, error) {
	rows, err := q.db.QueryContext(ctx, addUsersTraffic,
		pq.Array(arg.Ids),
		pq.Array(arg.Up),
		pq.Array(arg.Down),
		pq.Array(arg.PoolUp),
		pq.Array(arg.PoolDown),
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AddUsersTrafficRow{}
	for rows.Next() {
		var i AddUsersTrafficRow
		if err := rows.Scan(&i.ID, &i.TrafficLimit, &i.Used); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const burnUsersSlots = `-- name: BurnUsersSlots :exec
UPDATE slots SET state = 'burned', burned_at = $1
WHERE id IN (SELECT slot_id FROM users WHERE id = ANY($2::bigint[]) AND slot_id IS NOT NULL
             UNION SELECT slot_id FROM bound_devices WHERE user_id = ANY($2::bigint[]) AND hwid <> '')
`

type BurnUsersSlotsParams struct {
	BurnedAt sql.NullInt64
	Ids      []int64
}

// The slots of these users and of their registered bound devices stop working.
func (q *Queries) BurnUsersSlots(ctx context.Context, arg BurnUsersSlotsParams) error {
	_, err := q.db.ExecContext(ctx, burnUsersSlots, arg.BurnedAt, pq.Array(arg.Ids))
	return err
}

const countBoundDevicesOf = `-- name: CountBoundDevicesOf :many
SELECT user_id, count(*) AS n FROM bound_devices WHERE user_id = ANY($1::bigint[]) GROUP BY user_id
`

type CountBoundDevicesOfRow struct {
	UserID int64
	N      int64
}

// How many devices are bound to each of these users: the places they take.
func (q *Queries) CountBoundDevicesOf(ctx context.Context, ids []int64) ([]CountBoundDevicesOfRow, error) {
	rows, err := q.db.QueryContext(ctx, countBoundDevicesOf, pq.Array(ids))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountBoundDevicesOfRow{}
	for rows.Next() {
		var i CountBoundDevicesOfRow
		if err := rows.Scan(&i.UserID, &i.N); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countUserStates = `-- name: CountUserStates :one
WITH g AS (
  SELECT user_id, SUM(remaining) AS left_bytes FROM traffic_grants
  WHERE pool_id IS NULL AND remaining > 0 AND (expires_at IS NULL OR expires_at > $1::bigint)
  GROUP BY user_id
), s AS (
  SELECT CASE
    WHEN u.status = 'disabled' THEN 'disabled'
    WHEN u.expires_at IS NOT NULL AND u.expires_at <= $1::bigint THEN 'expired'
    WHEN u.traffic_limit IS NOT NULL AND u.used_up + u.used_down >= u.traffic_limit AND COALESCE(g.left_bytes, 0) <= 0 THEN 'limited'
    WHEN u.expires_at IS NOT NULL AND u.expires_at - $1::bigint <= $2::bigint THEN 'expiring'
    ELSE 'active' END AS state
  FROM users u LEFT JOIN g ON g.user_id = u.id
)
SELECT count(*) AS total,
  count(*) FILTER (WHERE state = 'active') AS active,
  count(*) FILTER (WHERE state = 'expiring') AS expiring,
  count(*) FILTER (WHERE state = 'limited') AS limited,
  count(*) FILTER (WHERE state = 'expired') AS expired,
  count(*) FILTER (WHERE state = 'disabled') AS disabled
FROM s
`

type CountUserStatesParams struct {
	Now            int64
	ExpiringWithin int64
}

type CountUserStatesRow struct {
	Total    int64
	Active   int64
	Expiring int64
	Limited  int64
	Expired  int64
	Disabled int64
}

// How many users are in each state as domain.State decides it (keep the two alike):
// disabled, expired, limited (past the base quota with no main grants left), expiring
// (the term ends within expiring_within seconds), otherwise active.
func (q *Queries) CountUserStates(ctx context.Context, arg CountUserStatesParams) (CountUserStatesRow, error) {
	row := q.db.QueryRowContext(ctx, countUserStates, arg.Now, arg.ExpiringWithin)
	var i CountUserStatesRow
	err := row.Scan(
		&i.Total,
		&i.Active,
		&i.Expiring,
		&i.Limited,
		&i.Expired,
		&i.Disabled,
	)
	return i, err
}

const countersPositions = `-- name: CountersPositions :many
SELECT key, value FROM node_state WHERE key LIKE 'counters\_epoch/%' OR key LIKE 'counters\_seq/%'
`

// Every node's counters position: counters_epoch/<node> and counters_seq/<node>.
func (q *Queries) CountersPositions(ctx context.Context) ([]NodeState, error) {
	rows, err := q.db.QueryContext(ctx, countersPositions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NodeState{}
	for rows.Next() {
		var i NodeState
		if err := rows.Scan(&i.Key, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteUsers = `-- name: DeleteUsers :exec
DELETE FROM users WHERE id = ANY($1::bigint[])
`

func (q *Queries) DeleteUsers(ctx context.Context, ids []int64) error {
	_, err := q.db.ExecContext(ctx, deleteUsers, pq.Array(ids))
	return err
}

const deleteUsersBoundDevices = `-- name: DeleteUsersBoundDevices :exec
DELETE FROM bound_devices WHERE user_id = ANY($1::bigint[])
`

func (q *Queries) DeleteUsersBoundDevices(ctx context.Context, ids []int64) error {
	_, err := q.db.ExecContext(ctx, deleteUsersBoundDevices, pq.Array(ids))
	return err
}

const endUsersPeriodGrants = `-- name: EndUsersPeriodGrants :exec
UPDATE traffic_grants SET expires_at = CAST($1 AS BIGINT)
WHERE user_id = ANY($2::bigint[]) AND lifetime = 'period' AND remaining > 0
  AND (expires_at IS NULL OR expires_at > CAST($1 AS BIGINT))
`

type EndUsersPeriodGrantsParams struct {
	Now int64
	Ids []int64
}

func (q *Queries) EndUsersPeriodGrants(ctx context.Context, arg EndUsersPeriodGrantsParams) error {
	_, err := q.db.ExecContext(ctx, endUsersPeriodGrants, arg.Now, pq.Array(arg.Ids))
	return err
}

const inboundEventsAfter = `-- name: InboundEventsAfter :many
SELECT id, inbound_id, node_id, kind, network, old_value, new_value, reason, created_at FROM inbound_events WHERE id > $1 ORDER BY id LIMIT 500
`

// The automatic changes after a cursor, oldest first, a page at a time.
func (q *Queries) InboundEventsAfter(ctx context.Context, id int64) ([]InboundEvent, error) {
	rows, err := q.db.QueryContext(ctx, inboundEventsAfter, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InboundEvent{}
	for rows.Next() {
		var i InboundEvent
		if err := rows.Scan(
			&i.ID,
			&i.InboundID,
			&i.NodeID,
			&i.Kind,
			&i.Network,
			&i.OldValue,
			&i.NewValue,
			&i.Reason,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertSlots = `-- name: InsertSlots :exec
INSERT INTO slots (name, uuid, secret, state, created_at)
SELECT unnest($1::text[]), unnest($2::text[]), unnest($3::text[]), 'free', $4::bigint
`

type InsertSlotsParams struct {
	Names     []string
	Uuids     []string
	Secrets   []string
	CreatedAt int64
}

func (q *Queries) InsertSlots(ctx context.Context, arg InsertSlotsParams) error {
	_, err := q.db.ExecContext(ctx, insertSlots,
		pq.Array(arg.Names),
		pq.Array(arg.Uuids),
		pq.Array(arg.Secrets),
		arg.CreatedAt,
	)
	return err
}

const listNoticeSubscriptions = `-- name: ListNoticeSubscriptions :many
SELECT users.id, users.name, users.contact, users.note, users.tags, users.status, users.tariff_id, users.traffic_limit, users.device_limit, users.reset_strategy, users.period_days, users.period_start, users.used_up, users.used_down, users.total_up, users.total_down, users.expires_at, users.inbounds, users.sub_token, users.slot_id, users.online_at, users.created_at, users.updated_at, users.billing_day, users.unbound_at, users.source, users.hidden, users.folder_id, users.speed_limit, l.tg_id, CAST(COALESCE(g.left_bytes, 0) AS BIGINT) AS grants_left
FROM tg_links l
JOIN users ON users.id = l.user_id
LEFT JOIN tg_chats c ON c.tg_id = l.tg_id
LEFT JOIN (SELECT user_id, SUM(remaining) AS left_bytes FROM traffic_grants
           WHERE pool_id IS NULL AND remaining > 0 AND (expires_at IS NULL OR expires_at > $1::bigint)
           GROUP BY user_id) g ON g.user_id = users.id
WHERE COALESCE(c.blocked, 0) = 0
ORDER BY users.id
`

type ListNoticeSubscriptionsRow struct {
	User       User
	TgID       int64
	GrantsLeft int64
}

// The subscriptions the bot may tell about (linked, the chat not blocked) with what is
// left of their main grants: one read for a round of notices.
func (q *Queries) ListNoticeSubscriptions(ctx context.Context, now int64) ([]ListNoticeSubscriptionsRow, error) {
	rows, err := q.db.QueryContext(ctx, listNoticeSubscriptions, now)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListNoticeSubscriptionsRow{}
	for rows.Next() {
		var i ListNoticeSubscriptionsRow
		if err := rows.Scan(
			&i.User.ID,
			&i.User.Name,
			&i.User.Contact,
			&i.User.Note,
			&i.User.Tags,
			&i.User.Status,
			&i.User.TariffID,
			&i.User.TrafficLimit,
			&i.User.DeviceLimit,
			&i.User.ResetStrategy,
			&i.User.PeriodDays,
			&i.User.PeriodStart,
			&i.User.UsedUp,
			&i.User.UsedDown,
			&i.User.TotalUp,
			&i.User.TotalDown,
			&i.User.ExpiresAt,
			&i.User.Inbounds,
			&i.User.SubToken,
			&i.User.SlotID,
			&i.User.OnlineAt,
			&i.User.CreatedAt,
			&i.User.UpdatedAt,
			&i.User.BillingDay,
			&i.User.UnboundAt,
			&i.User.Source,
			&i.User.Hidden,
			&i.User.FolderID,
			&i.User.SpeedLimit,
			&i.TgID,
			&i.GrantsLeft,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockBuyerInvoices = `-- name: LockBuyerInvoices :exec
SELECT pg_advisory_xact_lock(hashtextextended('mikan-invoice:' || CAST($1 AS BIGINT), 0))
`

// The invoices of one Telegram account are checked and made one transaction at a time.
func (q *Queries) LockBuyerInvoices(ctx context.Context, tgID int64) error {
	_, err := q.db.ExecContext(ctx, lockBuyerInvoices, tgID)
	return err
}

const lockSpendableGrants = `-- name: LockSpendableGrants :many
SELECT id, user_id, CAST(COALESCE(pool_id, 0) AS BIGINT) AS pool_id, remaining FROM traffic_grants
WHERE user_id = ANY($1::bigint[]) AND remaining > 0
  AND (expires_at IS NULL OR expires_at > CAST($2 AS BIGINT))
ORDER BY user_id, COALESCE(pool_id, 0), expires_at IS NULL, expires_at, created_at, id
FOR NO KEY UPDATE
`

type LockSpendableGrantsParams struct {
	UserIds []int64
	Now     int64
}

type LockSpendableGrantsRow struct {
	ID        int64
	UserID    int64
	PoolID    int64
	Remaining int64
}

// The active grants of these users in the spending order of each target (pool 0: the
// main traffic), locked: traffic past a base quota is taken from them.
func (q *Queries) LockSpendableGrants(ctx context.Context, arg LockSpendableGrantsParams) ([]LockSpendableGrantsRow, error) {
	rows, err := q.db.QueryContext(ctx, lockSpendableGrants, pq.Array(arg.UserIds), arg.Now)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LockSpendableGrantsRow{}
	for rows.Next() {
		var i LockSpendableGrantsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.PoolID,
			&i.Remaining,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockTrafficPools = `-- name: LockTrafficPools :many
SELECT id FROM traffic_pools WHERE id = ANY($1::bigint[]) ORDER BY id FOR KEY SHARE
`

// The pools of ids that exist; KEY SHARE keeps them from being deleted until the
// transaction ends, so the pool counters written after it cannot fail on one.
func (q *Queries) LockTrafficPools(ctx context.Context, ids []int64) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, lockTrafficPools, pq.Array(ids))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockUserRows = `-- name: LockUserRows :many
SELECT id, name, contact, note, tags, status, tariff_id, traffic_limit, device_limit, reset_strategy, period_days, period_start, used_up, used_down, total_up, total_down, expires_at, inbounds, sub_token, slot_id, online_at, created_at, updated_at, billing_day, unbound_at, source, hidden, folder_id, speed_limit FROM users WHERE id = ANY($1::bigint[]) ORDER BY id FOR NO KEY UPDATE
`

// The users of ids that exist, locked in id order for a change.
func (q *Queries) LockUserRows(ctx context.Context, ids []int64) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, lockUserRows, pq.Array(ids))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Contact,
			&i.Note,
			&i.Tags,
			&i.Status,
			&i.TariffID,
			&i.TrafficLimit,
			&i.DeviceLimit,
			&i.ResetStrategy,
			&i.PeriodDays,
			&i.PeriodStart,
			&i.UsedUp,
			&i.UsedDown,
			&i.TotalUp,
			&i.TotalDown,
			&i.ExpiresAt,
			&i.Inbounds,
			&i.SubToken,
			&i.SlotID,
			&i.OnlineAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.BillingDay,
			&i.UnboundAt,
			&i.Source,
			&i.Hidden,
			&i.FolderID,
			&i.SpeedLimit,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockUserRowsForDelete = `-- name: LockUserRowsForDelete :many
SELECT id, name, contact, note, tags, status, tariff_id, traffic_limit, device_limit, reset_strategy, period_days, period_start, used_up, used_down, total_up, total_down, expires_at, inbounds, sub_token, slot_id, online_at, created_at, updated_at, billing_day, unbound_at, source, hidden, folder_id, speed_limit FROM users WHERE id = ANY($1::bigint[]) ORDER BY id FOR UPDATE
`

func (q *Queries) LockUserRowsForDelete(ctx context.Context, ids []int64) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, lockUserRowsForDelete, pq.Array(ids))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Contact,
			&i.Note,
			&i.Tags,
			&i.Status,
			&i.TariffID,
			&i.TrafficLimit,
			&i.DeviceLimit,
			&i.ResetStrategy,
			&i.PeriodDays,
			&i.PeriodStart,
			&i.UsedUp,
			&i.UsedDown,
			&i.TotalUp,
			&i.TotalDown,
			&i.ExpiresAt,
			&i.Inbounds,
			&i.SubToken,
			&i.SlotID,
			&i.OnlineAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.BillingDay,
			&i.UnboundAt,
			&i.Source,
			&i.Hidden,
			&i.FolderID,
			&i.SpeedLimit,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockUsers = `-- name: LockUsers :many

SELECT id FROM users WHERE id = ANY($1::bigint[]) ORDER BY id FOR NO KEY UPDATE
`

// Set-based statements: one statement for many rows instead of one per row. Rows that
// other writers change too are locked in id order first, so two writers never wait for
// each other in a circle.
// The users of ids that exist, locked in id order until the transaction ends.
func (q *Queries) LockUsers(ctx context.Context, ids []int64) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, lockUsers, pq.Array(ids))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reserveSlotNumbers = `-- name: ReserveSlotNumbers :one
INSERT INTO slot_counter (id, last) VALUES (1, (SELECT coalesce(max(id), 0) FROM slots) + $1::bigint)
ON CONFLICT (id) DO UPDATE SET last = GREATEST(slot_counter.last, (SELECT coalesce(max(id), 0) FROM slots)) + $1::bigint
RETURNING last
`

// Moves the slot counter on by n and returns the last number reserved. Names go on from
// the last number ever handed out (the largest id for a counter that was never kept);
// concurrent refills wait on the counter's row and never get the same numbers.
func (q *Queries) ReserveSlotNumbers(ctx context.Context, n int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, reserveSlotNumbers, n)
	var last int64
	err := row.Scan(&last)
	return last, err
}

const resetUsersPools = `-- name: ResetUsersPools :exec
UPDATE user_pools SET used_up = 0, used_down = 0 WHERE user_id = ANY($1::bigint[])
`

func (q *Queries) ResetUsersPools(ctx context.Context, ids []int64) error {
	_, err := q.db.ExecContext(ctx, resetUsersPools, pq.Array(ids))
	return err
}

const resetUsersTraffic = `-- name: ResetUsersTraffic :exec
UPDATE users SET used_up = 0, used_down = 0, period_start = $1, updated_at = $1
WHERE id = ANY($2::bigint[])
`

type ResetUsersTrafficParams struct {
	Now int64
	Ids []int64
}

func (q *Queries) ResetUsersTraffic(ctx context.Context, arg ResetUsersTrafficParams) error {
	_, err := q.db.ExecContext(ctx, resetUsersTraffic, arg.Now, pq.Array(arg.Ids))
	return err
}

const setUsersExpiry = `-- name: SetUsersExpiry :exec
UPDATE users u SET expires_at = t.expires_at, status = 'active', updated_at = $1
FROM (SELECT unnest($2::bigint[]) AS id, unnest($3::bigint[]) AS expires_at) AS t
WHERE u.id = t.id
`

type SetUsersExpiryParams struct {
	UpdatedAt int64
	Ids       []int64
	ExpiresAt []int64
}

// A new term for each user; it also turns the user on.
func (q *Queries) SetUsersExpiry(ctx context.Context, arg SetUsersExpiryParams) error {
	_, err := q.db.ExecContext(ctx, setUsersExpiry, arg.UpdatedAt, pq.Array(arg.Ids), pq.Array(arg.ExpiresAt))
	return err
}

const setUsersOnline = `-- name: SetUsersOnline :exec
UPDATE users SET online_at = $1 WHERE id = ANY($2::bigint[])
`

type SetUsersOnlineParams struct {
	OnlineAt sql.NullInt64
	Ids      []int64
}

func (q *Queries) SetUsersOnline(ctx context.Context, arg SetUsersOnlineParams) error {
	_, err := q.db.ExecContext(ctx, setUsersOnline, arg.OnlineAt, pq.Array(arg.Ids))
	return err
}

const setUsersStatus = `-- name: SetUsersStatus :exec
UPDATE users SET status = $1, updated_at = $2 WHERE id = ANY($3::bigint[])
`

type SetUsersStatusParams struct {
	Status    string
	UpdatedAt int64
	Ids       []int64
}

func (q *Queries) SetUsersStatus(ctx context.Context, arg SetUsersStatusParams) error {
	_, err := q.db.ExecContext(ctx, setUsersStatus, arg.Status, arg.UpdatedAt, pq.Array(arg.Ids))
	return err
}

const slotOwners = `-- name: SlotOwners :many
SELECT s.name AS slot_name, u.id AS user_id FROM slots s JOIN users u ON u.slot_id = s.id
WHERE s.name = ANY($1::text[])
UNION
SELECT s.name AS slot_name, d.user_id AS user_id FROM slots s JOIN bound_devices d ON d.slot_id = s.id
WHERE s.name = ANY($1::text[])
`

type SlotOwnersRow struct {
	SlotName string
	UserID   int64
}

// The users of the named slots: the own slot and those of bound devices.
func (q *Queries) SlotOwners(ctx context.Context, names []string) ([]SlotOwnersRow, error) {
	rows, err := q.db.QueryContext(ctx, slotOwners, pq.Array(names))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SlotOwnersRow{}
	for rows.Next() {
		var i SlotOwnersRow
		if err := rows.Scan(&i.SlotName, &i.UserID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const spendGrants = `-- name: SpendGrants :exec
UPDATE traffic_grants g SET remaining = g.remaining - LEAST(g.remaining, t.spent)
FROM (SELECT unnest($1::bigint[]) AS id, unnest($2::bigint[]) AS spent) AS t
WHERE g.id = t.id
`

type SpendGrantsParams struct {
	Ids   []int64
	Spent []int64
}

func (q *Queries) SpendGrants(ctx context.Context, arg SpendGrantsParams) error {
	_, err := q.db.ExecContext(ctx, spendGrants, pq.Array(arg.Ids), pq.Array(arg.Spent))
	return err
}

const startPeriodIfOlder = `-- name: StartPeriodIfOlder :execrows
UPDATE users SET used_up = 0, used_down = 0, period_start = $1, updated_at = $2
WHERE id = $3 AND period_start < $1
`

type StartPeriodIfOlderParams struct {
	PeriodStart int64
	UpdatedAt   int64
	ID          int64
}

// A new traffic period over an older one only: a payment that started one meanwhile is
// not reset again.
func (q *Queries) StartPeriodIfOlder(ctx context.Context, arg StartPeriodIfOlderParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, startPeriodIfOlder, arg.PeriodStart, arg.UpdatedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const tgNoticeSent = `-- name: TgNoticeSent :one
SELECT EXISTS (SELECT 1 FROM tg_notices WHERE user_id = $1 AND kind = $2 AND period = $3)
`

type TgNoticeSentParams struct {
	UserID int64
	Kind   string
	Period int64
}

func (q *Queries) TgNoticeSent(ctx context.Context, arg TgNoticeSentParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, tgNoticeSent, arg.UserID, arg.Kind, arg.Period)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const upsertDevices = `-- name: UpsertDevices :exec
INSERT INTO devices (user_id, ip, first_seen, last_seen)
SELECT t.user_id, t.ip, $1::bigint, $1::bigint
FROM (SELECT unnest($2::bigint[]) AS user_id, unnest($3::text[]) AS ip) AS t
JOIN users u ON u.id = t.user_id
ORDER BY t.user_id, t.ip
ON CONFLICT (user_id, ip) DO UPDATE SET last_seen = excluded.last_seen
`

type UpsertDevicesParams struct {
	Now     int64
	UserIds []int64
	Ips     []string
}

// Devices seen online. A user deleted meanwhile is skipped: the rest still goes in.
func (q *Queries) UpsertDevices(ctx context.Context, arg UpsertDevicesParams) error {
	_, err := q.db.ExecContext(ctx, upsertDevices, arg.Now, pq.Array(arg.UserIds), pq.Array(arg.Ips))
	return err
}

const userSlotsOf = `-- name: UserSlotsOf :many
SELECT s.name AS slot_name, u.id AS user_id FROM slots s JOIN users u ON u.slot_id = s.id
WHERE u.id = ANY($1::bigint[])
UNION
SELECT s.name AS slot_name, d.user_id AS user_id FROM slots s JOIN bound_devices d ON d.slot_id = s.id
WHERE d.user_id = ANY($1::bigint[])
`

type UserSlotsOfRow struct {
	SlotName string
	UserID   int64
}

// The slots of these users: the own one and those of bound devices.
func (q *Queries) UserSlotsOf(ctx context.Context, ids []int64) ([]UserSlotsOfRow, error) {
	rows, err := q.db.QueryContext(ctx, userSlotsOf, pq.Array(ids))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserSlotsOfRow{}
	for rows.Next() {
		var i UserSlotsOfRow
		if err := rows.Scan(&i.SlotName, &i.UserID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
