// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: devices.sql

package db

import (
	"context"
	"database/sql"

	"github.com/lib/pq"
)

const addSlotsTraffic = `-- name: AddSlotsTraffic :exec
INSERT INTO slot_traffic (slot_id, up, down)
SELECT s.id, v.up, v.down
FROM (SELECT unnest($1::text[]) AS name, unnest($2::bigint[]) AS up, unnest($3::bigint[]) AS down) AS v
JOIN slots s ON s.name = v.name
ORDER BY s.id
ON CONFLICT (slot_id) DO UPDATE SET up = slot_traffic.up + excluded.up, down = slot_traffic.down + excluded.down
`

type AddSlotsTrafficParams struct {
	Names []string
	Up    []int64
	Down  []int64
}

// Adds a batch's traffic to its slots, in slot order so two nodes' batches take turns.
func (q *Queries) AddSlotsTraffic(ctx context.Context, arg AddSlotsTrafficParams) error {
	_, err := q.db.ExecContext(ctx, addSlotsTraffic, pq.Array(arg.Names), pq.Array(arg.Up), pq.Array(arg.Down))
	return err
}

const countBoundDevices = `-- name: CountBoundDevices :one
SELECT count(*) FROM bound_devices WHERE user_id = $1
`

func (q *Queries) CountBoundDevices(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countBoundDevices, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createBoundDevice = `-- name: CreateBoundDevice :one
INSERT INTO bound_devices (user_id, hwid, slot_id, os, os_version, model, app, last_ip, created_at, last_seen)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, user_id, hwid, slot_id, os, os_version, model, app, last_ip, created_at, last_seen, name
`

type CreateBoundDeviceParams struct {
	UserID    int64
	Hwid      string
	SlotID    int64
	Os        string
	OsVersion string
	Model     string
	App       string
	LastIp    string
	CreatedAt int64
	LastSeen  int64
}

func (q *Queries) CreateBoundDevice(ctx context.Context, arg CreateBoundDeviceParams) (BoundDevice, error) {
	row := q.db.QueryRowContext(ctx, createBoundDevice,
		arg.UserID,
		arg.Hwid,
		arg.SlotID,
		arg.Os,
		arg.OsVersion,
		arg.Model,
		arg.App,
		arg.LastIp,
		arg.CreatedAt,
		arg.LastSeen,
	)
	var i BoundDevice
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Hwid,
		&i.SlotID,
		&i.Os,
		&i.OsVersion,
		&i.Model,
		&i.App,
		&i.LastIp,
		&i.CreatedAt,
		&i.LastSeen,
		&i.Name,
	)
	return i, err
}

const createDeviceBan = `-- name: CreateDeviceBan :one
INSERT INTO device_bans (user_id, hwid, label, admin_id, banned_at)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (user_id, hwid) DO UPDATE SET label = EXCLUDED.label, admin_id = EXCLUDED.admin_id, banned_at = EXCLUDED.banned_at
RETURNING id, user_id, hwid, label, admin_id, banned_at
`

type CreateDeviceBanParams struct {
	UserID   int64
	Hwid     string
	Label    string
	AdminID  sql.NullInt64
	BannedAt int64
}

func (q *Queries) CreateDeviceBan(ctx context.Context, arg CreateDeviceBanParams) (DeviceBan, error) {
	row := q.db.QueryRowContext(ctx, createDeviceBan,
		arg.UserID,
		arg.Hwid,
		arg.Label,
		arg.AdminID,
		arg.BannedAt,
	)
	var i DeviceBan
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Hwid,
		&i.Label,
		&i.AdminID,
		&i.BannedAt,
	)
	return i, err
}

const deleteBoundDevice = `-- name: DeleteBoundDevice :exec
DELETE FROM bound_devices WHERE id = $1
`

func (q *Queries) DeleteBoundDevice(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteBoundDevice, id)
	return err
}

const deleteBoundDevicesOf = `-- name: DeleteBoundDevicesOf :exec
DELETE FROM bound_devices WHERE user_id = $1
`

func (q *Queries) DeleteBoundDevicesOf(ctx context.Context, userID int64) error {
	_, err := q.db.ExecContext(ctx, deleteBoundDevicesOf, userID)
	return err
}

const deleteDeviceBan = `-- name: DeleteDeviceBan :one
DELETE FROM device_bans WHERE id = $1 AND user_id = $2 RETURNING id, user_id, hwid, label, admin_id, banned_at
`

type DeleteDeviceBanParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) DeleteDeviceBan(ctx context.Context, arg DeleteDeviceBanParams) (DeviceBan, error) {
	row := q.db.QueryRowContext(ctx, deleteDeviceBan, arg.ID, arg.UserID)
	var i DeviceBan
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Hwid,
		&i.Label,
		&i.AdminID,
		&i.BannedAt,
	)
	return i, err
}

const deviceBanned = `-- name: DeviceBanned :one
SELECT EXISTS (SELECT 1 FROM device_bans WHERE user_id = $1 AND hwid = $2)
`

type DeviceBannedParams struct {
	UserID int64
	Hwid   string
}

func (q *Queries) DeviceBanned(ctx context.Context, arg DeviceBannedParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, deviceBanned, arg.UserID, arg.Hwid)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getBoundDevice = `-- name: GetBoundDevice :one
SELECT id, user_id, hwid, slot_id, os, os_version, model, app, last_ip, created_at, last_seen, name FROM bound_devices WHERE user_id = $1 AND hwid = $2
`

type GetBoundDeviceParams struct {
	UserID int64
	Hwid   string
}

func (q *Queries) GetBoundDevice(ctx context.Context, arg GetBoundDeviceParams) (BoundDevice, error) {
	row := q.db.QueryRowContext(ctx, getBoundDevice, arg.UserID, arg.Hwid)
	var i BoundDevice
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Hwid,
		&i.SlotID,
		&i.Os,
		&i.OsVersion,
		&i.Model,
		&i.App,
		&i.LastIp,
		&i.CreatedAt,
		&i.LastSeen,
		&i.Name,
	)
	return i, err
}

const getBoundDeviceByID = `-- name: GetBoundDeviceByID :one
SELECT id, user_id, hwid, slot_id, os, os_version, model, app, last_ip, created_at, last_seen, name FROM bound_devices WHERE id = $1 AND user_id = $2
`

type GetBoundDeviceByIDParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) GetBoundDeviceByID(ctx context.Context, arg GetBoundDeviceByIDParams) (BoundDevice, error) {
	row := q.db.QueryRowContext(ctx, getBoundDeviceByID, arg.ID, arg.UserID)
	var i BoundDevice
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Hwid,
		&i.SlotID,
		&i.Os,
		&i.OsVersion,
		&i.Model,
		&i.App,
		&i.LastIp,
		&i.CreatedAt,
		&i.LastSeen,
		&i.Name,
	)
	return i, err
}

const listBoundDeviceTraffic = `-- name: ListBoundDeviceTraffic :many
SELECT d.id AS device_id, COALESCE(t.up, 0)::bigint AS up, COALESCE(t.down, 0)::bigint AS down
FROM bound_devices d LEFT JOIN slot_traffic t ON t.slot_id = d.slot_id WHERE d.user_id = $1
`

type ListBoundDeviceTrafficRow struct {
	DeviceID int64
	Up       int64
	Down     int64
}

// What each of a user's bound devices used since it was bound.
func (q *Queries) ListBoundDeviceTraffic(ctx context.Context, userID int64) ([]ListBoundDeviceTrafficRow, error) {
	rows, err := q.db.QueryContext(ctx, listBoundDeviceTraffic, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBoundDeviceTrafficRow{}
	for rows.Next() {
		var i ListBoundDeviceTrafficRow
		if err := rows.Scan(&i.DeviceID, &i.Up, &i.Down); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBoundDevices = `-- name: ListBoundDevices :many
SELECT id, user_id, hwid, slot_id, os, os_version, model, app, last_ip, created_at, last_seen, name FROM bound_devices WHERE user_id = $1 ORDER BY created_at, id
`

func (q *Queries) ListBoundDevices(ctx context.Context, userID int64) ([]BoundDevice, error) {
	rows, err := q.db.QueryContext(ctx, listBoundDevices, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BoundDevice{}
	for rows.Next() {
		var i BoundDevice
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Hwid,
			&i.SlotID,
			&i.Os,
			&i.OsVersion,
			&i.Model,
			&i.App,
			&i.LastIp,
			&i.CreatedAt,
			&i.LastSeen,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeviceBans = `-- name: ListDeviceBans :many
SELECT b.id, b.user_id, b.hwid, b.label, b.admin_id, b.banned_at, COALESCE(a.username, '')::text AS admin_name
FROM device_bans b LEFT JOIN admins a ON a.id = b.admin_id
WHERE b.user_id = $1 ORDER BY b.banned_at DESC, b.id DESC
`

type ListDeviceBansRow struct {
	ID        int64
	UserID    int64
	Hwid      string
	Label     string
	AdminID   sql.NullInt64
	BannedAt  int64
	AdminName string
}

func (q *Queries) ListDeviceBans(ctx context.Context, userID int64) ([]ListDeviceBansRow, error) {
	rows, err := q.db.QueryContext(ctx, listDeviceBans, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDeviceBansRow{}
	for rows.Next() {
		var i ListDeviceBansRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Hwid,
			&i.Label,
			&i.AdminID,
			&i.BannedAt,
			&i.AdminName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeviceSlots = `-- name: ListDeviceSlots :many
SELECT s.name AS slot_name, d.user_id, d.last_seen FROM bound_devices d JOIN slots s ON s.id = d.slot_id WHERE d.hwid != ''
`

type ListDeviceSlotsRow struct {
	SlotName string
	UserID   int64
	LastSeen int64
}

// Slots of bound devices with an id: keys of their own, profile fetches of their own.
func (q *Queries) ListDeviceSlots(ctx context.Context) ([]ListDeviceSlotsRow, error) {
	rows, err := q.db.QueryContext(ctx, listDeviceSlots)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDeviceSlotsRow{}
	for rows.Next() {
		var i ListDeviceSlotsRow
		if err := rows.Scan(&i.SlotName, &i.UserID, &i.LastSeen); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIdleBoundDevices = `-- name: ListIdleBoundDevices :many
SELECT id, user_id, hwid, slot_id, os, os_version, model, app, last_ip, created_at, last_seen, name FROM bound_devices WHERE last_seen < $1
`

func (q *Queries) ListIdleBoundDevices(ctx context.Context, lastSeen int64) ([]BoundDevice, error) {
	rows, err := q.db.QueryContext(ctx, listIdleBoundDevices, lastSeen)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BoundDevice{}
	for rows.Next() {
		var i BoundDevice
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Hwid,
			&i.SlotID,
			&i.Os,
			&i.OsVersion,
			&i.Model,
			&i.App,
			&i.LastIp,
			&i.CreatedAt,
			&i.LastSeen,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setBoundDeviceName = `-- name: SetBoundDeviceName :execrows
UPDATE bound_devices SET name = $1 WHERE id = $2 AND user_id = $3
`

type SetBoundDeviceNameParams struct {
	Name   string
	ID     int64
	UserID int64
}

// The device's own name; ” goes back to the one its app reports.
func (q *Queries) SetBoundDeviceName(ctx context.Context, arg SetBoundDeviceNameParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setBoundDeviceName, arg.Name, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setUserSlot = `-- name: SetUserSlot :exec
UPDATE users SET slot_id = $1, updated_at = $2 WHERE id = $3
`

type SetUserSlotParams struct {
	SlotID    sql.NullInt64
	UpdatedAt int64
	ID        int64
}

// A new own slot for the user, same subscription link (the shared device was unbound).
func (q *Queries) SetUserSlot(ctx context.Context, arg SetUserSlotParams) error {
	_, err := q.db.ExecContext(ctx, setUserSlot, arg.SlotID, arg.UpdatedAt, arg.ID)
	return err
}

const setUserUnboundAt = `-- name: SetUserUnboundAt :exec
UPDATE users SET unbound_at = $1 WHERE id = $2
`

type SetUserUnboundAtParams struct {
	UnboundAt int64
	ID        int64
}

func (q *Queries) SetUserUnboundAt(ctx context.Context, arg SetUserUnboundAtParams) error {
	_, err := q.db.ExecContext(ctx, setUserUnboundAt, arg.UnboundAt, arg.ID)
	return err
}

const touchBoundDevice = `-- name: TouchBoundDevice :exec
UPDATE bound_devices SET os = $1, os_version = $2, model = $3, app = $4, last_ip = $5, last_seen = $6 WHERE id = $7
`

type TouchBoundDeviceParams struct {
	Os        string
	OsVersion string
	Model     string
	App       string
	LastIp    string
	LastSeen  int64
	ID        int64
}

func (q *Queries) TouchBoundDevice(ctx context.Context, arg TouchBoundDeviceParams) error {
	_, err := q.db.ExecContext(ctx, touchBoundDevice,
		arg.Os,
		arg.OsVersion,
		arg.Model,
		arg.App,
		arg.LastIp,
		arg.LastSeen,
		arg.ID,
	)
	return err
}
