// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: domain.sql

package db

import (
	"context"
	"database/sql"
)

const addTariffTerm = `-- name: AddTariffTerm :exec
INSERT INTO tariff_terms (tariff_id, days, price_stars, price_rub, sort) VALUES ($1, $2, $3, $4, $5)
`

type AddTariffTermParams struct {
	TariffID   int64
	Days       int64
	PriceStars sql.NullInt64
	PriceRub   sql.NullInt64
	Sort       int64
}

func (q *Queries) AddTariffTerm(ctx context.Context, arg AddTariffTermParams) error {
	_, err := q.db.ExecContext(ctx, addTariffTerm,
		arg.TariffID,
		arg.Days,
		arg.PriceStars,
		arg.PriceRub,
		arg.Sort,
	)
	return err
}

const addTrafficDaily = `-- name: AddTrafficDaily :exec
INSERT INTO traffic_daily (user_id, day, up, down) VALUES ($1, $2, $3, $4)
ON CONFLICT (user_id, day) DO UPDATE SET up = traffic_daily.up + excluded.up, down = traffic_daily.down + excluded.down
`

type AddTrafficDailyParams struct {
	UserID int64
	Day    int64
	Up     int64
	Down   int64
}

func (q *Queries) AddTrafficDaily(ctx context.Context, arg AddTrafficDailyParams) error {
	_, err := q.db.ExecContext(ctx, addTrafficDaily,
		arg.UserID,
		arg.Day,
		arg.Up,
		arg.Down,
	)
	return err
}

const addTrafficHourly = `-- name: AddTrafficHourly :exec
INSERT INTO traffic_hourly (user_id, hour, up, down) VALUES ($1, $2, $3, $4)
ON CONFLICT (user_id, hour) DO UPDATE SET up = traffic_hourly.up + excluded.up, down = traffic_hourly.down + excluded.down
`

type AddTrafficHourlyParams struct {
	UserID int64
	Hour   int64
	Up     int64
	Down   int64
}

func (q *Queries) AddTrafficHourly(ctx context.Context, arg AddTrafficHourlyParams) error {
	_, err := q.db.ExecContext(ctx, addTrafficHourly,
		arg.UserID,
		arg.Hour,
		arg.Up,
		arg.Down,
	)
	return err
}

const addUserTraffic = `-- name: AddUserTraffic :exec
UPDATE users
SET used_up = used_up + $1, used_down = used_down + $2,
    total_up = total_up + $1, total_down = total_down + $2
WHERE id = $3
`

type AddUserTrafficParams struct {
	Up   int64
	Down int64
	ID   int64
}

func (q *Queries) AddUserTraffic(ctx context.Context, arg AddUserTrafficParams) error {
	_, err := q.db.ExecContext(ctx, addUserTraffic, arg.Up, arg.Down, arg.ID)
	return err
}

const archiveTariff = `-- name: ArchiveTariff :execrows
UPDATE tariffs SET archived = 1 WHERE id = $1
`

func (q *Queries) ArchiveTariff(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, archiveTariff, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const burnSlot = `-- name: BurnSlot :exec
UPDATE slots SET state = 'burned', burned_at = $1 WHERE id = $2
`

type BurnSlotParams struct {
	BurnedAt sql.NullInt64
	ID       int64
}

func (q *Queries) BurnSlot(ctx context.Context, arg BurnSlotParams) error {
	_, err := q.db.ExecContext(ctx, burnSlot, arg.BurnedAt, arg.ID)
	return err
}

const countSlotsByState = `-- name: CountSlotsByState :many
SELECT state, count(*) AS n FROM slots GROUP BY state
`

type CountSlotsByStateRow struct {
	State string
	N     int64
}

func (q *Queries) CountSlotsByState(ctx context.Context) ([]CountSlotsByStateRow, error) {
	rows, err := q.db.QueryContext(ctx, countSlotsByState)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountSlotsByStateRow{}
	for rows.Next() {
		var i CountSlotsByStateRow
		if err := rows.Scan(&i.State, &i.N); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countTariffs = `-- name: CountTariffs :one
SELECT count(*) FROM tariffs
`

func (q *Queries) CountTariffs(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTariffs)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createInbound = `-- name: CreateInbound :one
INSERT INTO inbounds (node_id, name, preset, port, enabled, settings, config, created_at, updated_at)
VALUES ($1, $2, $3, $4, 1, '{}', $5, $6, $7)
RETURNING id, node_id, name, preset, port, enabled, settings, created_at, updated_at, display_name, config, auto_port, auto_sni, outbound, exit_node_id, pool_id, listen
`

type CreateInboundParams struct {
	NodeID    int64
	Name      string
	Preset    string
	Port      string
	Config    string
	CreatedAt int64
	UpdatedAt int64
}

func (q *Queries) CreateInbound(ctx context.Context, arg CreateInboundParams) (Inbound, error) {
	row := q.db.QueryRowContext(ctx, createInbound,
		arg.NodeID,
		arg.Name,
		arg.Preset,
		arg.Port,
		arg.Config,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Inbound
	err := row.Scan(
		&i.ID,
		&i.NodeID,
		&i.Name,
		&i.Preset,
		&i.Port,
		&i.Enabled,
		&i.Settings,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DisplayName,
		&i.Config,
		&i.AutoPort,
		&i.AutoSni,
		&i.Outbound,
		&i.ExitNodeID,
		&i.PoolID,
		&i.Listen,
	)
	return i, err
}

const createTariff = `-- name: CreateTariff :one
INSERT INTO tariffs (name, traffic_limit, duration_days, device_limit, reset_strategy, price_label, sort, created_at, billing_day, price_stars, price_rub, on_sale)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING id, name, traffic_limit, duration_days, device_limit, reset_strategy, price_label, sort, archived, created_at, billing_day, price_stars, price_rub, on_sale
`

type CreateTariffParams struct {
	Name          string
	TrafficLimit  sql.NullInt64
	DurationDays  int64
	DeviceLimit   sql.NullInt64
	ResetStrategy string
	PriceLabel    string
	Sort          int64
	CreatedAt     int64
	BillingDay    sql.NullInt64
	PriceStars    sql.NullInt64
	PriceRub      sql.NullInt64
	OnSale        int64
}

func (q *Queries) CreateTariff(ctx context.Context, arg CreateTariffParams) (Tariff, error) {
	row := q.db.QueryRowContext(ctx, createTariff,
		arg.Name,
		arg.TrafficLimit,
		arg.DurationDays,
		arg.DeviceLimit,
		arg.ResetStrategy,
		arg.PriceLabel,
		arg.Sort,
		arg.CreatedAt,
		arg.BillingDay,
		arg.PriceStars,
		arg.PriceRub,
		arg.OnSale,
	)
	var i Tariff
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TrafficLimit,
		&i.DurationDays,
		&i.DeviceLimit,
		&i.ResetStrategy,
		&i.PriceLabel,
		&i.Sort,
		&i.Archived,
		&i.CreatedAt,
		&i.BillingDay,
		&i.PriceStars,
		&i.PriceRub,
		&i.OnSale,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (name, contact, note, tags, status, tariff_id, traffic_limit, device_limit, reset_strategy,
                   period_days, period_start, expires_at, inbounds, sub_token, slot_id, created_at, updated_at, billing_day)
VALUES ($1, $2, $3, $4, 'active', $5, $6, $7, $8, $9, $10, $11, NULL, $12, $13, $14, $15, $16)
RETURNING id, name, contact, note, tags, status, tariff_id, traffic_limit, device_limit, reset_strategy, period_days, period_start, used_up, used_down, total_up, total_down, expires_at, inbounds, sub_token, slot_id, online_at, created_at, updated_at, billing_day, unbound_at
`

type CreateUserParams struct {
	Name          string
	Contact       string
	Note          string
	Tags          string
	TariffID      sql.NullInt64
	TrafficLimit  sql.NullInt64
	DeviceLimit   sql.NullInt64
	ResetStrategy string
	PeriodDays    int64
	PeriodStart   int64
	ExpiresAt     sql.NullInt64
	SubToken      string
	SlotID        sql.NullInt64
	CreatedAt     int64
	UpdatedAt     int64
	BillingDay    sql.NullInt64
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.Name,
		arg.Contact,
		arg.Note,
		arg.Tags,
		arg.TariffID,
		arg.TrafficLimit,
		arg.DeviceLimit,
		arg.ResetStrategy,
		arg.PeriodDays,
		arg.PeriodStart,
		arg.ExpiresAt,
		arg.SubToken,
		arg.SlotID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.BillingDay,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Contact,
		&i.Note,
		&i.Tags,
		&i.Status,
		&i.TariffID,
		&i.TrafficLimit,
		&i.DeviceLimit,
		&i.ResetStrategy,
		&i.PeriodDays,
		&i.PeriodStart,
		&i.UsedUp,
		&i.UsedDown,
		&i.TotalUp,
		&i.TotalDown,
		&i.ExpiresAt,
		&i.Inbounds,
		&i.SubToken,
		&i.SlotID,
		&i.OnlineAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BillingDay,
		&i.UnboundAt,
	)
	return i, err
}

const deleteBurnedSlots = `-- name: DeleteBurnedSlots :exec
DELETE FROM slots WHERE state = 'burned' AND id NOT IN (SELECT slot_id FROM users WHERE slot_id IS NOT NULL)
  AND id NOT IN (SELECT slot_id FROM bound_devices)
`

func (q *Queries) DeleteBurnedSlots(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteBurnedSlots)
	return err
}

const deleteInbound = `-- name: DeleteInbound :exec
DELETE FROM inbounds WHERE id = $1
`

func (q *Queries) DeleteInbound(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteInbound, id)
	return err
}

const deleteNodeStateOf = `-- name: DeleteNodeStateOf :exec
DELETE FROM node_state WHERE key LIKE '%/' || CAST($1 AS TEXT)
`

func (q *Queries) DeleteNodeStateOf(ctx context.Context, nodeID string) error {
	_, err := q.db.ExecContext(ctx, deleteNodeStateOf, nodeID)
	return err
}

const deleteTariffTerms = `-- name: DeleteTariffTerms :exec
DELETE FROM tariff_terms WHERE tariff_id = $1
`

func (q *Queries) DeleteTariffTerms(ctx context.Context, tariffID int64) error {
	_, err := q.db.ExecContext(ctx, deleteTariffTerms, tariffID)
	return err
}

const getInbound = `-- name: GetInbound :one
SELECT id, node_id, name, preset, port, enabled, settings, created_at, updated_at, display_name, config, auto_port, auto_sni, outbound, exit_node_id, pool_id, listen FROM inbounds WHERE id = $1
`

func (q *Queries) GetInbound(ctx context.Context, id int64) (Inbound, error) {
	row := q.db.QueryRowContext(ctx, getInbound, id)
	var i Inbound
	err := row.Scan(
		&i.ID,
		&i.NodeID,
		&i.Name,
		&i.Preset,
		&i.Port,
		&i.Enabled,
		&i.Settings,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DisplayName,
		&i.Config,
		&i.AutoPort,
		&i.AutoSni,
		&i.Outbound,
		&i.ExitNodeID,
		&i.PoolID,
		&i.Listen,
	)
	return i, err
}

const getNodeState = `-- name: GetNodeState :one
SELECT value FROM node_state WHERE key = $1
`

func (q *Queries) GetNodeState(ctx context.Context, key string) (string, error) {
	row := q.db.QueryRowContext(ctx, getNodeState, key)
	var value string
	err := row.Scan(&value)
	return value, err
}

const getSlot = `-- name: GetSlot :one
SELECT id, name, uuid, secret, state, created_at, burned_at FROM slots WHERE id = $1
`

func (q *Queries) GetSlot(ctx context.Context, id int64) (Slot, error) {
	row := q.db.QueryRowContext(ctx, getSlot, id)
	var i Slot
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Uuid,
		&i.Secret,
		&i.State,
		&i.CreatedAt,
		&i.BurnedAt,
	)
	return i, err
}

const getTariff = `-- name: GetTariff :one
SELECT id, name, traffic_limit, duration_days, device_limit, reset_strategy, price_label, sort, archived, created_at, billing_day, price_stars, price_rub, on_sale FROM tariffs WHERE id = $1
`

func (q *Queries) GetTariff(ctx context.Context, id int64) (Tariff, error) {
	row := q.db.QueryRowContext(ctx, getTariff, id)
	var i Tariff
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TrafficLimit,
		&i.DurationDays,
		&i.DeviceLimit,
		&i.ResetStrategy,
		&i.PriceLabel,
		&i.Sort,
		&i.Archived,
		&i.CreatedAt,
		&i.BillingDay,
		&i.PriceStars,
		&i.PriceRub,
		&i.OnSale,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, name, contact, note, tags, status, tariff_id, traffic_limit, device_limit, reset_strategy, period_days, period_start, used_up, used_down, total_up, total_down, expires_at, inbounds, sub_token, slot_id, online_at, created_at, updated_at, billing_day, unbound_at FROM users WHERE id = $1
`

func (q *Queries) GetUser(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Contact,
		&i.Note,
		&i.Tags,
		&i.Status,
		&i.TariffID,
		&i.TrafficLimit,
		&i.DeviceLimit,
		&i.ResetStrategy,
		&i.PeriodDays,
		&i.PeriodStart,
		&i.UsedUp,
		&i.UsedDown,
		&i.TotalUp,
		&i.TotalDown,
		&i.ExpiresAt,
		&i.Inbounds,
		&i.SubToken,
		&i.SlotID,
		&i.OnlineAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BillingDay,
		&i.UnboundAt,
	)
	return i, err
}

const getUserBySubToken = `-- name: GetUserBySubToken :one
SELECT id, name, contact, note, tags, status, tariff_id, traffic_limit, device_limit, reset_strategy, period_days, period_start, used_up, used_down, total_up, total_down, expires_at, inbounds, sub_token, slot_id, online_at, created_at, updated_at, billing_day, unbound_at FROM users WHERE sub_token = $1
`

func (q *Queries) GetUserBySubToken(ctx context.Context, subToken string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserBySubToken, subToken)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Contact,
		&i.Note,
		&i.Tags,
		&i.Status,
		&i.TariffID,
		&i.TrafficLimit,
		&i.DeviceLimit,
		&i.ResetStrategy,
		&i.PeriodDays,
		&i.PeriodStart,
		&i.UsedUp,
		&i.UsedDown,
		&i.TotalUp,
		&i.TotalDown,
		&i.ExpiresAt,
		&i.Inbounds,
		&i.SubToken,
		&i.SlotID,
		&i.OnlineAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BillingDay,
		&i.UnboundAt,
	)
	return i, err
}

const insertSlot = `-- name: InsertSlot :exec
INSERT INTO slots (name, uuid, secret, state, created_at) VALUES ($1, $2, $3, 'free', $4)
`

type InsertSlotParams struct {
	Name      string
	Uuid      string
	Secret    string
	CreatedAt int64
}

func (q *Queries) InsertSlot(ctx context.Context, arg InsertSlotParams) error {
	_, err := q.db.ExecContext(ctx, insertSlot,
		arg.Name,
		arg.Uuid,
		arg.Secret,
		arg.CreatedAt,
	)
	return err
}

const listAllTariffTerms = `-- name: ListAllTariffTerms :many
SELECT id, tariff_id, days, price_stars, price_rub, sort FROM tariff_terms ORDER BY tariff_id, sort, id
`

func (q *Queries) ListAllTariffTerms(ctx context.Context) ([]TariffTerm, error) {
	rows, err := q.db.QueryContext(ctx, listAllTariffTerms)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TariffTerm{}
	for rows.Next() {
		var i TariffTerm
		if err := rows.Scan(
			&i.ID,
			&i.TariffID,
			&i.Days,
			&i.PriceStars,
			&i.PriceRub,
			&i.Sort,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBoundDeviceSlots = `-- name: ListBoundDeviceSlots :many
SELECT d.id AS device_id, s.name AS slot_name FROM bound_devices d JOIN slots s ON s.id = d.slot_id WHERE d.user_id = $1
`

type ListBoundDeviceSlotsRow struct {
	DeviceID int64
	SlotName string
}

// The names of the slots of a user's bound devices, by device id.
func (q *Queries) ListBoundDeviceSlots(ctx context.Context, userID int64) ([]ListBoundDeviceSlotsRow, error) {
	rows, err := q.db.QueryContext(ctx, listBoundDeviceSlots, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBoundDeviceSlotsRow{}
	for rows.Next() {
		var i ListBoundDeviceSlotsRow
		if err := rows.Scan(&i.DeviceID, &i.SlotName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInbounds = `-- name: ListInbounds :many
SELECT id, node_id, name, preset, port, enabled, settings, created_at, updated_at, display_name, config, auto_port, auto_sni, outbound, exit_node_id, pool_id, listen FROM inbounds ORDER BY id
`

func (q *Queries) ListInbounds(ctx context.Context) ([]Inbound, error) {
	rows, err := q.db.QueryContext(ctx, listInbounds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Inbound{}
	for rows.Next() {
		var i Inbound
		if err := rows.Scan(
			&i.ID,
			&i.NodeID,
			&i.Name,
			&i.Preset,
			&i.Port,
			&i.Enabled,
			&i.Settings,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DisplayName,
			&i.Config,
			&i.AutoPort,
			&i.AutoSni,
			&i.Outbound,
			&i.ExitNodeID,
			&i.PoolID,
			&i.Listen,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNodeInbounds = `-- name: ListNodeInbounds :many
SELECT id, node_id, name, preset, port, enabled, settings, created_at, updated_at, display_name, config, auto_port, auto_sni, outbound, exit_node_id, pool_id, listen FROM inbounds WHERE node_id = $1 ORDER BY id
`

func (q *Queries) ListNodeInbounds(ctx context.Context, nodeID int64) ([]Inbound, error) {
	rows, err := q.db.QueryContext(ctx, listNodeInbounds, nodeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Inbound{}
	for rows.Next() {
		var i Inbound
		if err := rows.Scan(
			&i.ID,
			&i.NodeID,
			&i.Name,
			&i.Preset,
			&i.Port,
			&i.Enabled,
			&i.Settings,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DisplayName,
			&i.Config,
			&i.AutoPort,
			&i.AutoSni,
			&i.Outbound,
			&i.ExitNodeID,
			&i.PoolID,
			&i.Listen,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSlotUsers = `-- name: ListSlotUsers :many
SELECT s.name AS slot_name, u.id AS user_id FROM slots s JOIN users u ON u.slot_id = s.id
UNION
SELECT s.name AS slot_name, d.user_id AS user_id FROM slots s JOIN bound_devices d ON d.slot_id = s.id
`

type ListSlotUsersRow struct {
	SlotName string
	UserID   int64
}

// Every slot that works for a user: the own one and those of bound devices.
func (q *Queries) ListSlotUsers(ctx context.Context) ([]ListSlotUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, listSlotUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSlotUsersRow{}
	for rows.Next() {
		var i ListSlotUsersRow
		if err := rows.Scan(&i.SlotName, &i.UserID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSlots = `-- name: ListSlots :many
SELECT id, name, uuid, secret, state, created_at, burned_at FROM slots ORDER BY id
`

func (q *Queries) ListSlots(ctx context.Context) ([]Slot, error) {
	rows, err := q.db.QueryContext(ctx, listSlots)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Slot{}
	for rows.Next() {
		var i Slot
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Uuid,
			&i.Secret,
			&i.State,
			&i.CreatedAt,
			&i.BurnedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTariffTerms = `-- name: ListTariffTerms :many
SELECT id, tariff_id, days, price_stars, price_rub, sort FROM tariff_terms WHERE tariff_id = $1 ORDER BY sort, id
`

func (q *Queries) ListTariffTerms(ctx context.Context, tariffID int64) ([]TariffTerm, error) {
	rows, err := q.db.QueryContext(ctx, listTariffTerms, tariffID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TariffTerm{}
	for rows.Next() {
		var i TariffTerm
		if err := rows.Scan(
			&i.ID,
			&i.TariffID,
			&i.Days,
			&i.PriceStars,
			&i.PriceRub,
			&i.Sort,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTariffs = `-- name: ListTariffs :many
SELECT id, name, traffic_limit, duration_days, device_limit, reset_strategy, price_label, sort, archived, created_at, billing_day, price_stars, price_rub, on_sale FROM tariffs WHERE archived = 0 ORDER BY sort, id
`

func (q *Queries) ListTariffs(ctx context.Context) ([]Tariff, error) {
	rows, err := q.db.QueryContext(ctx, listTariffs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tariff{}
	for rows.Next() {
		var i Tariff
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.TrafficLimit,
			&i.DurationDays,
			&i.DeviceLimit,
			&i.ResetStrategy,
			&i.PriceLabel,
			&i.Sort,
			&i.Archived,
			&i.CreatedAt,
			&i.BillingDay,
			&i.PriceStars,
			&i.PriceRub,
			&i.OnSale,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserDevices = `-- name: ListUserDevices :many
SELECT user_id, ip, first_seen, last_seen FROM devices WHERE user_id = $1 ORDER BY last_seen DESC
`

func (q *Queries) ListUserDevices(ctx context.Context, userID int64) ([]Device, error) {
	rows, err := q.db.QueryContext(ctx, listUserDevices, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Device{}
	for rows.Next() {
		var i Device
		if err := rows.Scan(
			&i.UserID,
			&i.Ip,
			&i.FirstSeen,
			&i.LastSeen,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserSlots = `-- name: ListUserSlots :many
SELECT s.name FROM slots s JOIN users u ON u.slot_id = s.id WHERE u.id = $1
UNION
SELECT s.name FROM slots s JOIN bound_devices d ON d.slot_id = s.id WHERE d.user_id = $1
`

// The same for one user: what an answer about a single user needs, not the whole table.
func (q *Queries) ListUserSlots(ctx context.Context, userID int64) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listUserSlots, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, name, contact, note, tags, status, tariff_id, traffic_limit, device_limit, reset_strategy, period_days, period_start, used_up, used_down, total_up, total_down, expires_at, inbounds, sub_token, slot_id, online_at, created_at, updated_at, billing_day, unbound_at FROM users ORDER BY id DESC
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Contact,
			&i.Note,
			&i.Tags,
			&i.Status,
			&i.TariffID,
			&i.TrafficLimit,
			&i.DeviceLimit,
			&i.ResetStrategy,
			&i.PeriodDays,
			&i.PeriodStart,
			&i.UsedUp,
			&i.UsedDown,
			&i.TotalUp,
			&i.TotalDown,
			&i.ExpiresAt,
			&i.Inbounds,
			&i.SubToken,
			&i.SlotID,
			&i.OnlineAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.BillingDay,
			&i.UnboundAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pruneDevices = `-- name: PruneDevices :exec
DELETE FROM devices WHERE last_seen < $1
`

func (q *Queries) PruneDevices(ctx context.Context, lastSeen int64) error {
	_, err := q.db.ExecContext(ctx, pruneDevices, lastSeen)
	return err
}

const pruneTrafficDaily = `-- name: PruneTrafficDaily :exec
DELETE FROM traffic_daily WHERE day < $1
`

func (q *Queries) PruneTrafficDaily(ctx context.Context, day int64) error {
	_, err := q.db.ExecContext(ctx, pruneTrafficDaily, day)
	return err
}

const pruneTrafficHourly = `-- name: PruneTrafficHourly :exec
DELETE FROM traffic_hourly WHERE hour < $1
`

func (q *Queries) PruneTrafficHourly(ctx context.Context, hour int64) error {
	_, err := q.db.ExecContext(ctx, pruneTrafficHourly, hour)
	return err
}

const resetUserTraffic = `-- name: ResetUserTraffic :exec
UPDATE users SET used_up = 0, used_down = 0, period_start = $1, updated_at = $2 WHERE id = $3
`

type ResetUserTrafficParams struct {
	PeriodStart int64
	UpdatedAt   int64
	ID          int64
}

func (q *Queries) ResetUserTraffic(ctx context.Context, arg ResetUserTrafficParams) error {
	_, err := q.db.ExecContext(ctx, resetUserTraffic, arg.PeriodStart, arg.UpdatedAt, arg.ID)
	return err
}

const setInboundConfig = `-- name: SetInboundConfig :exec
UPDATE inbounds SET config = $1 WHERE id = $2
`

type SetInboundConfigParams struct {
	Config string
	ID     int64
}

func (q *Queries) SetInboundConfig(ctx context.Context, arg SetInboundConfigParams) error {
	_, err := q.db.ExecContext(ctx, setInboundConfig, arg.Config, arg.ID)
	return err
}

const setNodeState = `-- name: SetNodeState :exec
INSERT INTO node_state (key, value) VALUES ($1, $2)
ON CONFLICT (key) DO UPDATE SET value = excluded.value
`

type SetNodeStateParams struct {
	Key   string
	Value string
}

func (q *Queries) SetNodeState(ctx context.Context, arg SetNodeStateParams) error {
	_, err := q.db.ExecContext(ctx, setNodeState, arg.Key, arg.Value)
	return err
}

const setUserCredentials = `-- name: SetUserCredentials :exec
UPDATE users SET slot_id = $1, sub_token = $2, updated_at = $3 WHERE id = $4
`

type SetUserCredentialsParams struct {
	SlotID    sql.NullInt64
	SubToken  string
	UpdatedAt int64
	ID        int64
}

func (q *Queries) SetUserCredentials(ctx context.Context, arg SetUserCredentialsParams) error {
	_, err := q.db.ExecContext(ctx, setUserCredentials,
		arg.SlotID,
		arg.SubToken,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const slotCounter = `-- name: SlotCounter :one
SELECT last FROM slot_counter WHERE id = 1
`

// The last slot number handed out: slots purged from the top do not give theirs back.
func (q *Queries) SlotCounter(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, slotCounter)
	var last int64
	err := row.Scan(&last)
	return last, err
}

const takeFreeSlot = `-- name: TakeFreeSlot :one
UPDATE slots SET state = 'assigned'
WHERE id = (SELECT id FROM slots WHERE state = 'free' ORDER BY id LIMIT 1 FOR UPDATE SKIP LOCKED) AND state = 'free'
RETURNING id, name, uuid, secret, state, created_at, burned_at
`

func (q *Queries) TakeFreeSlot(ctx context.Context) (Slot, error) {
	row := q.db.QueryRowContext(ctx, takeFreeSlot)
	var i Slot
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Uuid,
		&i.Secret,
		&i.State,
		&i.CreatedAt,
		&i.BurnedAt,
	)
	return i, err
}

const topUsersByTraffic = `-- name: TopUsersByTraffic :many
SELECT u.id, u.name, CAST(sum(d.up + d.down) AS BIGINT) AS bytes
FROM traffic_daily d JOIN users u ON u.id = d.user_id
WHERE d.day >= $1
GROUP BY u.id, u.name ORDER BY bytes DESC LIMIT CAST($2 AS BIGINT)
`

type TopUsersByTrafficParams struct {
	Day int64
	Lim int64
}

type TopUsersByTrafficRow struct {
	ID    int64
	Name  string
	Bytes int64
}

func (q *Queries) TopUsersByTraffic(ctx context.Context, arg TopUsersByTrafficParams) ([]TopUsersByTrafficRow, error) {
	rows, err := q.db.QueryContext(ctx, topUsersByTraffic, arg.Day, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TopUsersByTrafficRow{}
	for rows.Next() {
		var i TopUsersByTrafficRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Bytes); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const totalTrafficDaily = `-- name: TotalTrafficDaily :many
SELECT day, CAST(sum(up) AS BIGINT) AS up, CAST(sum(down) AS BIGINT) AS down
FROM traffic_daily WHERE day >= $1 GROUP BY day ORDER BY day
`

type TotalTrafficDailyRow struct {
	Day  int64
	Up   int64
	Down int64
}

func (q *Queries) TotalTrafficDaily(ctx context.Context, day int64) ([]TotalTrafficDailyRow, error) {
	rows, err := q.db.QueryContext(ctx, totalTrafficDaily, day)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TotalTrafficDailyRow{}
	for rows.Next() {
		var i TotalTrafficDailyRow
		if err := rows.Scan(&i.Day, &i.Up, &i.Down); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const totalTrafficHourly = `-- name: TotalTrafficHourly :many
SELECT hour, CAST(sum(up) AS BIGINT) AS up, CAST(sum(down) AS BIGINT) AS down
FROM traffic_hourly WHERE hour >= $1 GROUP BY hour ORDER BY hour
`

type TotalTrafficHourlyRow struct {
	Hour int64
	Up   int64
	Down int64
}

func (q *Queries) TotalTrafficHourly(ctx context.Context, hour int64) ([]TotalTrafficHourlyRow, error) {
	rows, err := q.db.QueryContext(ctx, totalTrafficHourly, hour)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TotalTrafficHourlyRow{}
	for rows.Next() {
		var i TotalTrafficHourlyRow
		if err := rows.Scan(&i.Hour, &i.Up, &i.Down); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateInbound = `-- name: UpdateInbound :one
UPDATE inbounds SET port = $1, enabled = $2, config = $3, display_name = $4, updated_at = $5 WHERE id = $6 RETURNING id, node_id, name, preset, port, enabled, settings, created_at, updated_at, display_name, config, auto_port, auto_sni, outbound, exit_node_id, pool_id, listen
`

type UpdateInboundParams struct {
	Port        string
	Enabled     int64
	Config      string
	DisplayName string
	UpdatedAt   int64
	ID          int64
}

func (q *Queries) UpdateInbound(ctx context.Context, arg UpdateInboundParams) (Inbound, error) {
	row := q.db.QueryRowContext(ctx, updateInbound,
		arg.Port,
		arg.Enabled,
		arg.Config,
		arg.DisplayName,
		arg.UpdatedAt,
		arg.ID,
	)
	var i Inbound
	err := row.Scan(
		&i.ID,
		&i.NodeID,
		&i.Name,
		&i.Preset,
		&i.Port,
		&i.Enabled,
		&i.Settings,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DisplayName,
		&i.Config,
		&i.AutoPort,
		&i.AutoSni,
		&i.Outbound,
		&i.ExitNodeID,
		&i.PoolID,
		&i.Listen,
	)
	return i, err
}

const updateTariff = `-- name: UpdateTariff :one
UPDATE tariffs
SET name = $1, traffic_limit = $2, duration_days = $3, device_limit = $4, reset_strategy = $5, price_label = $6, sort = $7, billing_day = $8,
    price_stars = $9, price_rub = $10, on_sale = $11
WHERE id = $12
RETURNING id, name, traffic_limit, duration_days, device_limit, reset_strategy, price_label, sort, archived, created_at, billing_day, price_stars, price_rub, on_sale
`

type UpdateTariffParams struct {
	Name          string
	TrafficLimit  sql.NullInt64
	DurationDays  int64
	DeviceLimit   sql.NullInt64
	ResetStrategy string
	PriceLabel    string
	Sort          int64
	BillingDay    sql.NullInt64
	PriceStars    sql.NullInt64
	PriceRub      sql.NullInt64
	OnSale        int64
	ID            int64
}

func (q *Queries) UpdateTariff(ctx context.Context, arg UpdateTariffParams) (Tariff, error) {
	row := q.db.QueryRowContext(ctx, updateTariff,
		arg.Name,
		arg.TrafficLimit,
		arg.DurationDays,
		arg.DeviceLimit,
		arg.ResetStrategy,
		arg.PriceLabel,
		arg.Sort,
		arg.BillingDay,
		arg.PriceStars,
		arg.PriceRub,
		arg.OnSale,
		arg.ID,
	)
	var i Tariff
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TrafficLimit,
		&i.DurationDays,
		&i.DeviceLimit,
		&i.ResetStrategy,
		&i.PriceLabel,
		&i.Sort,
		&i.Archived,
		&i.CreatedAt,
		&i.BillingDay,
		&i.PriceStars,
		&i.PriceRub,
		&i.OnSale,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET name = $1, contact = $2, note = $3, tags = $4, status = $5, tariff_id = $6, traffic_limit = $7, device_limit = $8,
    reset_strategy = $9, period_days = $10, period_start = $11, expires_at = $12, inbounds = $13, updated_at = $14, billing_day = $15
WHERE id = $16
RETURNING id, name, contact, note, tags, status, tariff_id, traffic_limit, device_limit, reset_strategy, period_days, period_start, used_up, used_down, total_up, total_down, expires_at, inbounds, sub_token, slot_id, online_at, created_at, updated_at, billing_day, unbound_at
`

type UpdateUserParams struct {
	Name          string
	Contact       string
	Note          string
	Tags          string
	Status        string
	TariffID      sql.NullInt64
	TrafficLimit  sql.NullInt64
	DeviceLimit   sql.NullInt64
	ResetStrategy string
	PeriodDays    int64
	PeriodStart   int64
	ExpiresAt     sql.NullInt64
	Inbounds      sql.NullString
	UpdatedAt     int64
	BillingDay    sql.NullInt64
	ID            int64
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUser,
		arg.Name,
		arg.Contact,
		arg.Note,
		arg.Tags,
		arg.Status,
		arg.TariffID,
		arg.TrafficLimit,
		arg.DeviceLimit,
		arg.ResetStrategy,
		arg.PeriodDays,
		arg.PeriodStart,
		arg.ExpiresAt,
		arg.Inbounds,
		arg.UpdatedAt,
		arg.BillingDay,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Contact,
		&i.Note,
		&i.Tags,
		&i.Status,
		&i.TariffID,
		&i.TrafficLimit,
		&i.DeviceLimit,
		&i.ResetStrategy,
		&i.PeriodDays,
		&i.PeriodStart,
		&i.UsedUp,
		&i.UsedDown,
		&i.TotalUp,
		&i.TotalDown,
		&i.ExpiresAt,
		&i.Inbounds,
		&i.SubToken,
		&i.SlotID,
		&i.OnlineAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BillingDay,
		&i.UnboundAt,
	)
	return i, err
}

const upsertDevice = `-- name: UpsertDevice :exec
INSERT INTO devices (user_id, ip, first_seen, last_seen) VALUES ($1, $2, $3, $4)
ON CONFLICT (user_id, ip) DO UPDATE SET last_seen = excluded.last_seen
`

type UpsertDeviceParams struct {
	UserID    int64
	Ip        string
	FirstSeen int64
	LastSeen  int64
}

func (q *Queries) UpsertDevice(ctx context.Context, arg UpsertDeviceParams) error {
	_, err := q.db.ExecContext(ctx, upsertDevice,
		arg.UserID,
		arg.Ip,
		arg.FirstSeen,
		arg.LastSeen,
	)
	return err
}

const userTrafficDaily = `-- name: UserTrafficDaily :many
SELECT day, up, down FROM traffic_daily WHERE user_id = $1 AND day >= $2 ORDER BY day
`

type UserTrafficDailyParams struct {
	UserID int64
	Day    int64
}

type UserTrafficDailyRow struct {
	Day  int64
	Up   int64
	Down int64
}

func (q *Queries) UserTrafficDaily(ctx context.Context, arg UserTrafficDailyParams) ([]UserTrafficDailyRow, error) {
	rows, err := q.db.QueryContext(ctx, userTrafficDaily, arg.UserID, arg.Day)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserTrafficDailyRow{}
	for rows.Next() {
		var i UserTrafficDailyRow
		if err := rows.Scan(&i.Day, &i.Up, &i.Down); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const userTrafficHourly = `-- name: UserTrafficHourly :many
SELECT hour, up, down FROM traffic_hourly WHERE user_id = $1 AND hour >= $2 ORDER BY hour
`

type UserTrafficHourlyParams struct {
	UserID int64
	Hour   int64
}

type UserTrafficHourlyRow struct {
	Hour int64
	Up   int64
	Down int64
}

func (q *Queries) UserTrafficHourly(ctx context.Context, arg UserTrafficHourlyParams) ([]UserTrafficHourlyRow, error) {
	rows, err := q.db.QueryContext(ctx, userTrafficHourly, arg.UserID, arg.Hour)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserTrafficHourlyRow{}
	for rows.Next() {
		var i UserTrafficHourlyRow
		if err := rows.Scan(&i.Hour, &i.Up, &i.Down); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
