// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: legacy.sql

package db

import (
	"context"

	"github.com/lib/pq"
)

const addLegacySubToken = `-- name: AddLegacySubToken :execrows
INSERT INTO legacy_sub_tokens (token, user_id, source, not_before) VALUES ($1, $2, $3, $4)
ON CONFLICT (token) DO NOTHING
`

type AddLegacySubTokenParams struct {
	Token     string
	UserID    int64
	Source    string
	NotBefore int64
}

func (q *Queries) AddLegacySubToken(ctx context.Context, arg AddLegacySubTokenParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, addLegacySubToken,
		arg.Token,
		arg.UserID,
		arg.Source,
		arg.NotBefore,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const countLegacySubTokens = `-- name: CountLegacySubTokens :one
SELECT count(*) FROM legacy_sub_tokens
`

func (q *Queries) CountLegacySubTokens(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countLegacySubTokens)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteLegacySubTokensOf = `-- name: DeleteLegacySubTokensOf :exec
DELETE FROM legacy_sub_tokens WHERE user_id = $1
`

func (q *Queries) DeleteLegacySubTokensOf(ctx context.Context, userID int64) error {
	_, err := q.db.ExecContext(ctx, deleteLegacySubTokensOf, userID)
	return err
}

const legacySubTokenUser = `-- name: LegacySubTokenUser :one
SELECT u.id, u.name, u.contact, u.note, u.tags, u.status, u.tariff_id, u.traffic_limit, u.device_limit, u.reset_strategy, u.period_days, u.period_start, u.used_up, u.used_down, u.total_up, u.total_down, u.expires_at, u.inbounds, u.sub_token, u.slot_id, u.online_at, u.created_at, u.updated_at, u.billing_day, u.unbound_at, u.source, u.hidden, u.folder_id, u.speed_limit, t.not_before FROM legacy_sub_tokens t JOIN users u ON u.id = t.user_id WHERE t.token = $1
`

type LegacySubTokenUserRow struct {
	User      User
	NotBefore int64
}

func (q *Queries) LegacySubTokenUser(ctx context.Context, token string) (LegacySubTokenUserRow, error) {
	row := q.db.QueryRowContext(ctx, legacySubTokenUser, token)
	var i LegacySubTokenUserRow
	err := row.Scan(
		&i.User.ID,
		&i.User.Name,
		&i.User.Contact,
		&i.User.Note,
		&i.User.Tags,
		&i.User.Status,
		&i.User.TariffID,
		&i.User.TrafficLimit,
		&i.User.DeviceLimit,
		&i.User.ResetStrategy,
		&i.User.PeriodDays,
		&i.User.PeriodStart,
		&i.User.UsedUp,
		&i.User.UsedDown,
		&i.User.TotalUp,
		&i.User.TotalDown,
		&i.User.ExpiresAt,
		&i.User.Inbounds,
		&i.User.SubToken,
		&i.User.SlotID,
		&i.User.OnlineAt,
		&i.User.CreatedAt,
		&i.User.UpdatedAt,
		&i.User.BillingDay,
		&i.User.UnboundAt,
		&i.User.Source,
		&i.User.Hidden,
		&i.User.FolderID,
		&i.User.SpeedLimit,
		&i.NotBefore,
	)
	return i, err
}

const listLegacySubTokensOf = `-- name: ListLegacySubTokensOf :many
SELECT token, source FROM legacy_sub_tokens WHERE user_id = $1 ORDER BY token
`

type ListLegacySubTokensOfRow struct {
	Token  string
	Source string
}

func (q *Queries) ListLegacySubTokensOf(ctx context.Context, userID int64) ([]ListLegacySubTokensOfRow, error) {
	rows, err := q.db.QueryContext(ctx, listLegacySubTokensOf, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLegacySubTokensOfRow{}
	for rows.Next() {
		var i ListLegacySubTokensOfRow
		if err := rows.Scan(&i.Token, &i.Source); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockUserName = `-- name: LockUserName :exec
SELECT pg_advisory_xact_lock(hashtextextended('mikan-user-name:' || $1::text, 0))
`

// Holds a name until the transaction ends: two imports (or retries) at once cannot both
// find it free.
func (q *Queries) LockUserName(ctx context.Context, name string) error {
	_, err := q.db.ExecContext(ctx, lockUserName, name)
	return err
}

const setImportedUsage = `-- name: SetImportedUsage :exec
UPDATE users SET used_down = $2, total_down = $3, updated_at = $4 WHERE id = $1
`

type SetImportedUsageParams struct {
	ID        int64
	UsedDown  int64
	TotalDown int64
	UpdatedAt int64
}

func (q *Queries) SetImportedUsage(ctx context.Context, arg SetImportedUsageParams) error {
	_, err := q.db.ExecContext(ctx, setImportedUsage,
		arg.ID,
		arg.UsedDown,
		arg.TotalDown,
		arg.UpdatedAt,
	)
	return err
}

const takenUserNames = `-- name: TakenUserNames :many
SELECT DISTINCT name FROM users WHERE name = ANY($1::text[])
`

func (q *Queries) TakenUserNames(ctx context.Context, names []string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, takenUserNames, pq.Array(names))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const userNameTaken = `-- name: UserNameTaken :one
SELECT EXISTS (SELECT 1 FROM users WHERE name = $1)
`

func (q *Queries) UserNameTaken(ctx context.Context, name string) (bool, error) {
	row := q.db.QueryRowContext(ctx, userNameTaken, name)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
