// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: nodes.sql

package db

import (
	"context"
	"database/sql"
)

const createNode = `-- name: CreateNode :one
INSERT INTO nodes (name, address, public_host, domain, cert_sha256, enabled, created_at, updated_at, sort)
VALUES ($1, $2, $3, $4, $5, 1, $6, $7, (SELECT COALESCE(MAX(sort), 0) + 1 FROM nodes))
RETURNING id, name, address, public_host, domain, cert_sha256, enabled, created_at, updated_at, public_name, sort, total_up, total_down, fair_share, channel_mbps
`

type CreateNodeParams struct {
	Name       string
	Address    string
	PublicHost string
	Domain     string
	CertSha256 string
	CreatedAt  int64
	UpdatedAt  int64
}

// A new node goes last in the subscription.
func (q *Queries) CreateNode(ctx context.Context, arg CreateNodeParams) (Node, error) {
	row := q.db.QueryRowContext(ctx, createNode,
		arg.Name,
		arg.Address,
		arg.PublicHost,
		arg.Domain,
		arg.CertSha256,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.PublicHost,
		&i.Domain,
		&i.CertSha256,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PublicName,
		&i.Sort,
		&i.TotalUp,
		&i.TotalDown,
		&i.FairShare,
		&i.ChannelMbps,
	)
	return i, err
}

const deleteNode = `-- name: DeleteNode :exec
DELETE FROM nodes WHERE id = $1 AND id != 1
`

func (q *Queries) DeleteNode(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteNode, id)
	return err
}

const getNode = `-- name: GetNode :one
SELECT id, name, address, public_host, domain, cert_sha256, enabled, created_at, updated_at, public_name, sort, total_up, total_down, fair_share, channel_mbps FROM nodes WHERE id = $1
`

func (q *Queries) GetNode(ctx context.Context, id int64) (Node, error) {
	row := q.db.QueryRowContext(ctx, getNode, id)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.PublicHost,
		&i.Domain,
		&i.CertSha256,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PublicName,
		&i.Sort,
		&i.TotalUp,
		&i.TotalDown,
		&i.FairShare,
		&i.ChannelMbps,
	)
	return i, err
}

const listNodes = `-- name: ListNodes :many
SELECT id, name, address, public_host, domain, cert_sha256, enabled, created_at, updated_at, public_name, sort, total_up, total_down, fair_share, channel_mbps FROM nodes ORDER BY sort, id
`

func (q *Queries) ListNodes(ctx context.Context) ([]Node, error) {
	rows, err := q.db.QueryContext(ctx, listNodes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Node{}
	for rows.Next() {
		var i Node
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Address,
			&i.PublicHost,
			&i.Domain,
			&i.CertSha256,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PublicName,
			&i.Sort,
			&i.TotalUp,
			&i.TotalDown,
			&i.FairShare,
			&i.ChannelMbps,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setNodeCert = `-- name: SetNodeCert :exec
UPDATE nodes SET cert_sha256 = $1, updated_at = $2 WHERE id = $3
`

type SetNodeCertParams struct {
	CertSha256 string
	UpdatedAt  int64
	ID         int64
}

func (q *Queries) SetNodeCert(ctx context.Context, arg SetNodeCertParams) error {
	_, err := q.db.ExecContext(ctx, setNodeCert, arg.CertSha256, arg.UpdatedAt, arg.ID)
	return err
}

const setNodeShaping = `-- name: SetNodeShaping :exec
UPDATE nodes SET fair_share = $1, channel_mbps = $2, updated_at = $3 WHERE id = $4
`

type SetNodeShapingParams struct {
	FairShare   int64
	ChannelMbps sql.NullInt64
	UpdatedAt   int64
	ID          int64
}

func (q *Queries) SetNodeShaping(ctx context.Context, arg SetNodeShapingParams) error {
	_, err := q.db.ExecContext(ctx, setNodeShaping,
		arg.FairShare,
		arg.ChannelMbps,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const setNodeSort = `-- name: SetNodeSort :exec
UPDATE nodes SET sort = $1 WHERE id = $2
`

type SetNodeSortParams struct {
	Sort int64
	ID   int64
}

func (q *Queries) SetNodeSort(ctx context.Context, arg SetNodeSortParams) error {
	_, err := q.db.ExecContext(ctx, setNodeSort, arg.Sort, arg.ID)
	return err
}

const updateNode = `-- name: UpdateNode :one
UPDATE nodes SET name = $1, address = $2, public_host = $3, domain = $4, public_name = $5, enabled = $6, updated_at = $7 WHERE id = $8 RETURNING id, name, address, public_host, domain, cert_sha256, enabled, created_at, updated_at, public_name, sort, total_up, total_down, fair_share, channel_mbps
`

type UpdateNodeParams struct {
	Name       string
	Address    string
	PublicHost string
	Domain     string
	PublicName string
	Enabled    int64
	UpdatedAt  int64
	ID         int64
}

func (q *Queries) UpdateNode(ctx context.Context, arg UpdateNodeParams) (Node, error) {
	row := q.db.QueryRowContext(ctx, updateNode,
		arg.Name,
		arg.Address,
		arg.PublicHost,
		arg.Domain,
		arg.PublicName,
		arg.Enabled,
		arg.UpdatedAt,
		arg.ID,
	)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.PublicHost,
		&i.Domain,
		&i.CertSha256,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PublicName,
		&i.Sort,
		&i.TotalUp,
		&i.TotalDown,
		&i.FairShare,
		&i.ChannelMbps,
	)
	return i, err
}
