// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: telegram.sql

package db

import (
	"context"
)

const addTgNotice = `-- name: AddTgNotice :execrows
INSERT INTO tg_notices (user_id, kind, period, sent_at) VALUES ($1, $2, $3, $4) ON CONFLICT DO NOTHING
`

type AddTgNoticeParams struct {
	UserID int64
	Kind   string
	Period int64
	SentAt int64
}

func (q *Queries) AddTgNotice(ctx context.Context, arg AddTgNoticeParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, addTgNotice,
		arg.UserID,
		arg.Kind,
		arg.Period,
		arg.SentAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const broadcastTargets = `-- name: BroadcastTargets :many
SELECT DISTINCT l.tg_id FROM tg_links l LEFT JOIN tg_chats c ON c.tg_id = l.tg_id WHERE COALESCE(c.blocked, 0) = 0
`

// Accounts with a linked subscription that did not block the bot.
func (q *Queries) BroadcastTargets(ctx context.Context) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, broadcastTargets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var tg_id int64
		if err := rows.Scan(&tg_id); err != nil {
			return nil, err
		}
		items = append(items, tg_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countTgChats = `-- name: CountTgChats :one
SELECT COUNT(DISTINCT tg_id) FROM tg_links
`

func (q *Queries) CountTgChats(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTgChats)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTgLinks = `-- name: CountTgLinks :one
SELECT COUNT(*) FROM tg_links
`

func (q *Queries) CountTgLinks(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTgLinks)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTgLinksOf = `-- name: CountTgLinksOf :one
SELECT COUNT(*) FROM tg_links WHERE tg_id = $1
`

func (q *Queries) CountTgLinksOf(ctx context.Context, tgID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTgLinksOf, tgID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getTgChat = `-- name: GetTgChat :one
SELECT tg_id, username, first_name, menu_msg_id, current, blocked, created_at, updated_at FROM tg_chats WHERE tg_id = $1
`

func (q *Queries) GetTgChat(ctx context.Context, tgID int64) (TgChat, error) {
	row := q.db.QueryRowContext(ctx, getTgChat, tgID)
	var i TgChat
	err := row.Scan(
		&i.TgID,
		&i.Username,
		&i.FirstName,
		&i.MenuMsgID,
		&i.Current,
		&i.Blocked,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTgLink = `-- name: GetTgLink :one
SELECT user_id, tg_id, created_at FROM tg_links WHERE user_id = $1
`

func (q *Queries) GetTgLink(ctx context.Context, userID int64) (TgLink, error) {
	row := q.db.QueryRowContext(ctx, getTgLink, userID)
	var i TgLink
	err := row.Scan(&i.UserID, &i.TgID, &i.CreatedAt)
	return i, err
}

const linkTg = `-- name: LinkTg :exec
INSERT INTO tg_links (user_id, tg_id, created_at) VALUES ($1, $2, $3)
ON CONFLICT (user_id) DO UPDATE SET tg_id = excluded.tg_id, created_at = excluded.created_at
`

type LinkTgParams struct {
	UserID    int64
	TgID      int64
	CreatedAt int64
}

func (q *Queries) LinkTg(ctx context.Context, arg LinkTgParams) error {
	_, err := q.db.ExecContext(ctx, linkTg, arg.UserID, arg.TgID, arg.CreatedAt)
	return err
}

const listTgLinksOf = `-- name: ListTgLinksOf :many
SELECT u.id, u.name, u.contact, u.note, u.tags, u.status, u.tariff_id, u.traffic_limit, u.device_limit, u.reset_strategy, u.period_days, u.period_start, u.used_up, u.used_down, u.total_up, u.total_down, u.expires_at, u.inbounds, u.sub_token, u.slot_id, u.online_at, u.created_at, u.updated_at, u.billing_day, u.unbound_at, u.source, u.hidden, u.folder_id, u.speed_limit FROM tg_links l JOIN users u ON u.id = l.user_id WHERE l.tg_id = $1 ORDER BY l.created_at, u.id
`

// The subscriptions a Telegram account owns, oldest link first.
func (q *Queries) ListTgLinksOf(ctx context.Context, tgID int64) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listTgLinksOf, tgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Contact,
			&i.Note,
			&i.Tags,
			&i.Status,
			&i.TariffID,
			&i.TrafficLimit,
			&i.DeviceLimit,
			&i.ResetStrategy,
			&i.PeriodDays,
			&i.PeriodStart,
			&i.UsedUp,
			&i.UsedDown,
			&i.TotalUp,
			&i.TotalDown,
			&i.ExpiresAt,
			&i.Inbounds,
			&i.SubToken,
			&i.SlotID,
			&i.OnlineAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.BillingDay,
			&i.UnboundAt,
			&i.Source,
			&i.Hidden,
			&i.FolderID,
			&i.SpeedLimit,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pruneTgNotices = `-- name: PruneTgNotices :exec
DELETE FROM tg_notices WHERE sent_at < $1
`

func (q *Queries) PruneTgNotices(ctx context.Context, sentAt int64) error {
	_, err := q.db.ExecContext(ctx, pruneTgNotices, sentAt)
	return err
}

const setTgBlocked = `-- name: SetTgBlocked :exec
UPDATE tg_chats SET blocked = $1 WHERE tg_id = $2
`

type SetTgBlockedParams struct {
	Blocked int64
	TgID    int64
}

func (q *Queries) SetTgBlocked(ctx context.Context, arg SetTgBlockedParams) error {
	_, err := q.db.ExecContext(ctx, setTgBlocked, arg.Blocked, arg.TgID)
	return err
}

const setTgCurrent = `-- name: SetTgCurrent :exec
UPDATE tg_chats SET current = $1 WHERE tg_id = $2
`

type SetTgCurrentParams struct {
	Current int64
	TgID    int64
}

func (q *Queries) SetTgCurrent(ctx context.Context, arg SetTgCurrentParams) error {
	_, err := q.db.ExecContext(ctx, setTgCurrent, arg.Current, arg.TgID)
	return err
}

const setTgMenu = `-- name: SetTgMenu :exec
UPDATE tg_chats SET menu_msg_id = $1 WHERE tg_id = $2
`

type SetTgMenuParams struct {
	MenuMsgID int64
	TgID      int64
}

func (q *Queries) SetTgMenu(ctx context.Context, arg SetTgMenuParams) error {
	_, err := q.db.ExecContext(ctx, setTgMenu, arg.MenuMsgID, arg.TgID)
	return err
}

const tgLinkOfUser = `-- name: TgLinkOfUser :one
SELECT l.tg_id, COALESCE(c.username, '') AS username, COALESCE(c.first_name, '') AS first_name
FROM tg_links l LEFT JOIN tg_chats c ON c.tg_id = l.tg_id WHERE l.user_id = $1
`

type TgLinkOfUserRow struct {
	TgID      int64
	Username  string
	FirstName string
}

func (q *Queries) TgLinkOfUser(ctx context.Context, userID int64) (TgLinkOfUserRow, error) {
	row := q.db.QueryRowContext(ctx, tgLinkOfUser, userID)
	var i TgLinkOfUserRow
	err := row.Scan(&i.TgID, &i.Username, &i.FirstName)
	return i, err
}

const unlinkTg = `-- name: UnlinkTg :exec
DELETE FROM tg_links WHERE user_id = $1
`

func (q *Queries) UnlinkTg(ctx context.Context, userID int64) error {
	_, err := q.db.ExecContext(ctx, unlinkTg, userID)
	return err
}

const upsertTgChat = `-- name: UpsertTgChat :exec
INSERT INTO tg_chats (tg_id, username, first_name, created_at, updated_at) VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (tg_id) DO UPDATE SET username = excluded.username, first_name = excluded.first_name, blocked = 0, updated_at = excluded.updated_at
`

type UpsertTgChatParams struct {
	TgID      int64
	Username  string
	FirstName string
	CreatedAt int64
	UpdatedAt int64
}

func (q *Queries) UpsertTgChat(ctx context.Context, arg UpsertTgChatParams) error {
	_, err := q.db.ExecContext(ctx, upsertTgChat,
		arg.TgID,
		arg.Username,
		arg.FirstName,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
