// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: trials.sql

package db

import (
	"context"
	"database/sql"
)

const countTrials = `-- name: CountTrials :one
SELECT count(*) FROM trials
`

func (q *Queries) CountTrials(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTrials)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const hasTrial = `-- name: HasTrial :one
SELECT EXISTS (SELECT 1 FROM trials WHERE tg_id = $1)
`

func (q *Queries) HasTrial(ctx context.Context, tgID int64) (bool, error) {
	row := q.db.QueryRowContext(ctx, hasTrial, tgID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const setTrialUser = `-- name: SetTrialUser :exec
UPDATE trials SET user_id = $1 WHERE tg_id = $2
`

type SetTrialUserParams struct {
	UserID sql.NullInt64
	TgID   int64
}

func (q *Queries) SetTrialUser(ctx context.Context, arg SetTrialUserParams) error {
	_, err := q.db.ExecContext(ctx, setTrialUser, arg.UserID, arg.TgID)
	return err
}

const takeTrial = `-- name: TakeTrial :execrows
INSERT INTO trials (tg_id, tariff_id, created_at) VALUES ($1, $2, $3) ON CONFLICT (tg_id) DO NOTHING
`

type TakeTrialParams struct {
	TgID      int64
	TariffID  sql.NullInt64
	CreatedAt int64
}

func (q *Queries) TakeTrial(ctx context.Context, arg TakeTrialParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, takeTrial, arg.TgID, arg.TariffID, arg.CreatedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
