-- +goose Up
-- A tariff sold for several terms (issue #17): each term has its days and prices. A tariff
-- with one term keeps it in its own duration_days, price_stars and price_rub and has no
-- rows here; with two or more, the rows are the terms and the tariff's columns repeat the
-- first one (the term an admin applies by hand). Days tell the terms of a tariff apart.
CREATE TABLE tariff_terms (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tariff_id   BIGINT NOT NULL REFERENCES tariffs(id) ON DELETE CASCADE,
  days        BIGINT NOT NULL CHECK (days >= 0),
  price_stars BIGINT CHECK (price_stars IS NULL OR price_stars > 0),
  price_rub   BIGINT CHECK (price_rub IS NULL OR price_rub > 0),
  sort        BIGINT NOT NULL DEFAULT 0,
  UNIQUE (tariff_id, days)
);

-- The term a payment bought, as bought: an edit of the tariff between the invoice and the
-- payment does not change it. NULL on payments made before: the tariff's own term.
ALTER TABLE payments ADD COLUMN term_days BIGINT;

-- +goose Down
ALTER TABLE payments DROP COLUMN term_days;
DROP TABLE tariff_terms;
