-- +goose Up
-- A bound device's own name, given by the admin or the subscriber; '' shows the name the
-- app reported (model, system, app).
ALTER TABLE bound_devices ADD COLUMN name TEXT NOT NULL DEFAULT '';

-- Devices the admin banned from a subscription by their id (x-hwid): such a device is
-- unbound and cannot bind to the same user again; its fetches get a notice instead of
-- keys. label is what the device was called when banned, as the device row is gone.
-- admin_id is who banned it; null when that admin is deleted since.
CREATE TABLE device_bans (
  id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id   BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  hwid      TEXT NOT NULL CHECK (hwid <> ''),
  label     TEXT NOT NULL DEFAULT '',
  admin_id  BIGINT REFERENCES admins(id) ON DELETE SET NULL,
  banned_at BIGINT NOT NULL,
  UNIQUE (user_id, hwid)
);

-- +goose Down
DROP TABLE device_bans;
ALTER TABLE bound_devices DROP COLUMN name;
