-- +goose Up
-- The subscriber's own unbinds, for the admin's limit of so many a period (domain.UnbindRules):
-- users.unbound_at kept only the last one, enough for "one a day" and no more.
CREATE TABLE device_unbinds (
  id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  at      BIGINT NOT NULL
);
CREATE INDEX device_unbinds_user_at ON device_unbinds (user_id, at);
INSERT INTO device_unbinds (user_id, at) SELECT id, unbound_at FROM users WHERE unbound_at > 0;
ALTER TABLE users DROP COLUMN unbound_at;

-- A ban until a moment: a device its subscriber unbound may not take a place again at once
-- (its app, still open, would fetch the subscription and bind again). NULL: for good, the
-- admin's ban.
ALTER TABLE device_bans ADD COLUMN until BIGINT;

-- +goose Down
DELETE FROM device_bans WHERE until IS NOT NULL;
ALTER TABLE device_bans DROP COLUMN until;
ALTER TABLE users ADD COLUMN unbound_at BIGINT NOT NULL DEFAULT 0;
UPDATE users u SET unbound_at = d.at FROM (SELECT user_id, max(at) AS at FROM device_unbinds GROUP BY user_id) d WHERE d.user_id = u.id;
DROP TABLE device_unbinds;
